version: '2'
services:
  code:
    build:
      context: .
      args:
        GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS
    command: bash install.sh apitest
    tty: true
    environment:
      - SISENSE_USERNAME=$SISENSE_USERNAME
      - SISENSE_PASSWORD=$SISENSE_PASSWORD
      - ENVIRONMENT=$ENVIRONMENT
      - DASHBOARDS=$DASHBOARDS
      - TEST_DATA=$TEST_DATA
      - FROM_ADDR=$FROM_ADDR
      - TO_ADDR=$TO_ADDR
      - FROM_PASSWORD=$FROM_PASSWORD
      - THREAD=$THREAD



